### ISSUE TITLE
Change Global Font

### ISSUE THREAD

**Issue by iamdarshshah** [iamdarshshah/hacktoberfest-participants#11]
### Acceptance criteria:
- change the fonts to look more pleasing
- recommended to use **Google fonts**

**Comment by matheuscr30** [comment]
Can i you assign this to me?

**Comment by iamdarshshah** [comment]
Sure, @matheuscr30 Go for it 👍

**Comment by matheuscr30** [comment]
Did the PR right here #12

**Comment by iamdarshshah** [comment]
> Hacktoberfest is not accepting this PR as valid

Which PR? #13 or #12

**Comment by matheuscr30** [comment]
#13

**Comment by ayush015** [comment]
If this issue is still open I would like to try it on !

**Comment by iamdarshshah** [comment]
Sure @ayush015 - Give it a try!

**Comment by ayush015** [comment]
@iamdarshshah added the new font #107
