### ISSUE TITLE
Fix characters (Å, Ä, Ö, Ø and so on)

### ISSUE THREAD

**Issue by FrejBjornsson** [iamdarshshah/hacktoberfest-participants#116]
**Is your feature request related to a problem? Please describe.**
The website won't show Scandinavian characters like Å, Ä and Ö.

**Describe the solution you'd like**
More supported characters.

**Describe alternatives you've considered**
Add UTF-8 or something that supports more characters.

**Additional context**
My full name won't display properly on the website (Frej Björnsson)

**Comment by iamdarshshah** [comment]
@FrejBjornsson Thanks, Would you like to work on this?

**Comment by FrejBjornsson** [comment]
Sure!

**Comment by FrejBjornsson** [comment]
I tried but it doesn't seem to work. Maybe someone else can take a look at it.

**Comment by FrejBjornsson** [comment]
Still doesn't show Ö though
