### ISSUE TITLE
💅 Change Modal styling

### ISSUE THREAD

**Issue by iamdarshshah** [iamdarshshah/hacktoberfest-participants#137]
**Current Stylings**
![Screenshot (53)](https://user-images.githubusercontent.com/25670841/96503539-089c5680-1271-11eb-8779-5c11e76501ae.png)

### Acceptance criteria
- [ ] Work on styling modal 
- [ ] It should be responsive
- [ ] Should use colors on basis of a theme change
- [ ] Update the modal scroll bar
- [ ] Add proper styling for list of PRs and `PRs Status`

GO, GIVE IT A TRY. 🚀

> Don't forget to ⭐ this repo. This will help us in reaching a wider audience. Also, do share it with your friends and colleagues,

**Thanks** 😄

**Comment by Emalsha** [comment]
I will try this (Y)

**Comment by Johnisaig** [comment]
I want to work on this, Please assign to me

**Comment by iamdarshshah** [comment]
@Emalsha & @Johnisaig You both can give it a try and will select the one which covers every criterion mentioned in the issue description 👍

**Comment by Emalsha** [comment]
#150

**Comment by Emalsha** [comment]
I did something like this ...
![image](https://user-images.githubusercontent.com/7451018/96939662-f8cd7e00-14cd-11eb-976e-7965bd5a16a2.png)
