### ISSUE TITLE
Add Search functionality

### ISSUE THREAD

**Issue by iamdarshshah** [iamdarshshah/hacktoberfest-participants#70]
**Hello Everyone!** 👋 

_Need to add a Search Functionality to the 🎃 Hacktoberfest Participants - Community project._ 

#### Acceptance criteria:

- [ ] Add a search bar ui
- [ ] Add incremental search functionality
- [ ] Search functionality should check these params to filter the list - `Name` & `Github-Username`.
- [ ] Search-bar should be responsive and added below `Create Pull Request` button, position must be center.

_GO, GIVE IT A TRY._ 🚀

> Don't forget to ⭐ this repo. This will help us in reaching a wider audience.

Thanks 😄

**Comment by shaalwan** [comment]
hey!i will do it!assign this to me.

**Comment by iamdarshshah** [comment]
@shaalwan Sure, Give it a try!

**Comment by pranesh239** [comment]
@iamdarshshah this issue is not yet assigned to anyone, I'd love to give this a try!

**Comment by iamdarshshah** [comment]
Sure, @pranesh239 Go for it!

**Comment by pranesh239** [comment]
#76 - I have raised this PR, @iamdarshshah please check

**Comment by SmitChavda** [comment]
I am also ready to do it if this issue is still open @iamdarshshah

**Comment by iamdarshshah** [comment]
#76 - resolved! Closing this as of now.
