### ISSUE TITLE
🐛 Fix Theme-switch issue on Page reload

### ISSUE THREAD

**Issue by iamdarshshah** [iamdarshshah/hacktoberfest-participants#97]
#### Steps to reproduce:
1. Visit the website i.e [ireact.tech](https://ireact.tech/)
2. by-default the selected theme would be `light`
3. toggle the theme-switch to `dark` mode
4. Reload the page and observe the `Switch` (It will be set to `light` but the theme would be `dark`)

> Note: This is working as expected locally. But, on the build, this issue persists.

##### Screenshot:
> Here, the selected theme is `Dark` but the theme-switch toggle points to the `light` theme.
![bug](https://user-images.githubusercontent.com/25670841/95679502-e65f6480-0bf0-11eb-97fd-e5174be7cd47.png)

##### Project Setup:
- Follow the mentioned steps in [CONTRIBUTING](https://github.com/iamdarshshah/hacktoberfest-participants/blob/master/CONTRIBUTING.md#%EF%B8%8F-project-setup) guidelines
- Test this on the build by executing [build commands](https://github.com/iamdarshshah/hacktoberfest-participants/blob/master/CONTRIBUTING.md#%EF%B8%8F-building-and-running-for-production).

_GO, GIVE IT A TRY._ 🚀

> Don't forget to ⭐ this repo. This will help us in reaching a wider audience. Also, do share it with your friends and colleagues,

**Thanks** 😄

**Comment by ayush015** [comment]
I want to try out fixing this issue . Can you assign me ?

**Comment by edwinfelipe** [comment]
I want to try to resolve it too

**Comment by iamdarshshah** [comment]
@ayush015 & @edwinfelipe Sure, Go for it! Will go through both of your submissions :+1:

**Comment by ayush015** [comment]
@iamdarshshah the same bug is not coming up in the development server ! How can i reproduce it

**Comment by edwinfelipe** [comment]
it only fail on the build project, i'm trying with the header component and I discover that when the page load on build de theme variable is undefined, for this component checked is false and the this is the cause the toogle button is wrong, now i am solving it

**Comment by iamdarshshah** [comment]
@edwinfelipe you get it correctly! @ayush015 - I have already mentioned it in the description that this works well locally, but we can reproduce this issue while working on build and you can also check the above mentioned description by @edwinfelipe 

Just find the work around for why this is happening and how we can solve this.

**Comment by edwinfelipe** [comment]
Take too long but, i made a pull request with a possible solution

**Comment by edwinfelipe** [comment]
I have a question? for this hacktoberfest  can I continue resolving bugs on this repo?

**Comment by iamdarshshah** [comment]
@edwinfelipe Sure, you can contribute to this project. Please check the open issues. For now, the priority is to solve #11 & Don't do it just for the sake of Hacktoberfest. Do it for making your contribution to be counted in the field of Open-Source.
