### ISSUE TITLE
🎃 Implement Pagination for the list of participants

### ISSUE THREAD

**Issue by iamdarshshah** [iamdarshshah/hacktoberfest-participants#99]
### Problem
Retrieving a list of all participants returns the entire set of participants with no ability for pagination. As our participant's list grows, this becomes an expensive operation, and to solve this pagination might help.

### Acceptance criteria:
- [ ] `noOfResults` should be **6** at a time
- [ ] Pagination component should include `next` & `prev` buttons with their respective functionality
- [ ] On `next` & `prev` - it should not re-render the whole website. Instead, it should just re-render the participant's list
- [ ] Pagination component's UI should work correctly on theme-switch
- [ ] It should follow the theme-colors as part of UI changes
- [ ] It should not affect the current `search` functionality i.e, irrespective of the page you're on, Search should work correctly
- [ ] Pagination component should be responsive and added about the footer element, the position must be `center` 

_GO, GIVE IT A TRY._ 🚀

> Don't forget to ⭐ this repo. This will help us in reaching a wider audience. Also, do share it with your friends and colleagues,

**Thanks** 😄

**Comment by lucas-barros** [comment]
I'll try this one

**Comment by iamdarshshah** [comment]
@lucas-barros Sure, Go for it!

**Comment by chandanky23** [comment]
on it

**Comment by edwinfelipe** [comment]
i will try this

**Comment by iamdarshshah** [comment]
@edwinfelipe Sure! Go for it.
